# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-24 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beltprac', '0003_auto_20190724_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='beltprac.Author'),
        ),
    ]
